# Generated by Django 3.1.2 on 2021-06-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20210606_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.board'),
            preserve_default=False,
        ),
    ]
