# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install brlapi
      run: |
        sudo apt update
        sudo apt install python3-brlapi
    - name: Install dependencies
      working-directory: ./pyban
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      working-directory: ./pyban
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with django test
      working-directory: ./pyban
      run: |
        python manage.py test tickets
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install app
      working-directory: ./app
      run: npm install
    - name: Run unit tests
      working-directory: ./app
      run: npm run test:unit
    - name: Run e2e tests
      working-directory: ./app
      run: |
        python ../pyban/manage.py migrate
        python ../pyban/manage.py runserver &
        sleep 5
        npm run test:e2e:headless
        pkill -f runserver
